services:
  webapp:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=""
      - REDIS_NO_SSL=True
#    command: pnpm dev --port 3000 --host 0.0.0.0
#    volumes:
#      - ./packages/webapp/package.json:/app/package.json
#      - ./packages/webapp/src:/app/src
#      - ./packages/webapp/static:/app/static
#      - ./packages/webapp/prisma:/app/prisma
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.tmp/cache:/data
